src/Uncas.NowSite.Web/Controllers/AuthenticationController.cs
using System.Configuration;
using System.Web.Mvc;
using System.Web.Security;
using Uncas.NowSite.Web.Models.InputModels;

namespace Uncas.NowSite.Web.Controllers
{
    public class AuthenticationController : BaseController
    {
        [HttpGet]
        public ActionResult LogOn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogOn(LogOnInputModel model)
        {
            if (model.UserName == ConfigurationManager.AppSettings["TestUser.UserName"] &&
                model.Password == ConfigurationManager.AppSettings["TestUser.Password"])
            {
                FormsAuthentication.SetAuthCookie(model.UserName, true);
                if (!string.IsNullOrWhiteSpace(model.ReturnUrl))
                {
                    return Redirect(model.ReturnUrl);
                }

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/Uncas.NowSite.Web/Controllers/BlogPostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SimpleCqrs.Commanding;
using Uncas.NowSite.Domain.BlogPosts.Commands;
using Uncas.NowSite.Domain.Infrastructure;
using Uncas.NowSite.Domain.Pictures.Commands;
using Uncas.NowSite.Domain.ReadModels;
using Uncas.NowSite.Web.Models.InputModels;

namespace Uncas.NowSite.Web.Controllers
{
    public class BlogPostController : BaseController
    {
        private readonly ICommandBus _commandBus;
        private readonly IReadStore _readStore;

        public BlogPostController(
            ICommandBus commandBus,
            IReadStore readStore)
        {
            _commandBus = commandBus;
            _readStore = readStore;
        }

        public ActionResult Index()
        {
            IEnumerable<BlogPostReadModel> blogPosts
                = _readStore.GetAll<BlogPostReadModel>();
            return View(blogPosts);
        }

        public ActionResult Details(Guid id)
        {
            BlogPostReadModel blogPost =
                _readStore.GetById<BlogPostReadModel>(id);
            return View(blogPost);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Admin()
        {
            IEnumerable<DeletedBlogPostModel> deletedPosts =
                _readStore.GetAll<DeletedBlogPostModel>();
            return View(deletedPosts);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            Guid id = Guid.NewGuid();
            var create = new CreateBlogPostCommand(id);
            _commandBus.Send(create);
            return RedirectToAction("Edit", new { id });
        }

        [Authorize]
        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var startEdit = new StartEditBlogPostCommand(id);
            _commandBus.Send(startEdit);
            EditBlogPostReadModel blogPost =
                _readStore.GetById<EditBlogPostReadModel>(id);
            return View(new EditBlogPostInputModel
            {
                Id = blogPost.Id,
                Title = blogPost.Title,
                Content = blogPost.Content,
                Pictures = blogPost.Pictures.Select(
                    x => new PictureInputModel
                    {
                        PictureId = x.Id,
                        PictureUrl = x.PictureUrl
                    })
            });
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(EditBlogPostInputModel model)
        {
            Guid id = model.Id;
            var addInfoCommand = new AddBlogPostInfoCommand(
               id,
               model.Title,
               model.Content);
            _commandBus.Send(addInfoCommand);
            var publishCommand = new PublishBlogPostCommand(id);
            _commandBus.Send(publishCommand);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            var deleteCommand = new DeleteBlogPostCommand(id);
            _commandBus.Send(deleteCommand);
            return RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Publish(Guid id)
        {
            var publishCommand = new PublishBlogPostCommand(id);
            _commandBus.Send(publishCommand);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult Replay()
        {
            _commandBus.Send(new SyncBlogPostsCommand());
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public ActionResult UploadPicture(
            Guid blogPostId,
            HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength == 0)
            {
                return Content("No file");
            }

            Guid pictureId = Guid.NewGuid();
            _commandBus.Send(new UploadPictureCommand
            {
                PictureId = pictureId,
                FileName = Path.GetFileName(file.FileName),
                FileStream = file.InputStream
            });

            _commandBus.Send(new AddPictureToBlogPostCommand
            {
                BlogPostId = blogPostId,
                PictureId = pictureId
            });

            return RedirectToAction("Edit", new { id = blogPostId });
        }
    }
}

src/Uncas.NowSite.Web/Controllers/FactController.cs
using System;
using System.Web.Mvc;
using SimpleCqrs.Commanding;
using Uncas.NowSite.Domain.Facts.Commands;
using Uncas.NowSite.Domain.Infrastructure;
using Uncas.NowSite.Domain.ReadModels;

namespace Uncas.NowSite.Web.Controllers
{
    [Authorize]
    public class FactController : Controller
    {
        private readonly ICommandBus _commandBus;
        private readonly IReadStore _readStore;

        public FactController(
            ICommandBus commandBus,
            IReadStore readStore)
        {
            _commandBus = commandBus;
            _readStore = readStore;
        }

        public ActionResult Index()
        {
            var facts = _readStore.GetAll<FactReadModel>();
            return View(facts);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateFactCommand command)
        {
            command.Id = Guid.NewGuid();
            _commandBus.Send(command);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(Guid id)
        {
            var fact = _readStore.GetById<FactReadModel>(id);
            return View(fact);
        }

        [HttpPost]
        public ActionResult Edit(EditFactCommand command)
        {
            _commandBus.Send(command);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(DeleteFactCommand command)
        {
            _commandBus.Send(command);
            return RedirectToAction("Index");
        }
    }
}

src/Uncas.NowSite.Web/Views/Shared/_Layout.cshtml
@using StackExchange.Profiling;
<!DOCTYPE html>
<html lang="da">
<head>
    <meta charset="utf-8" />
    <meta name="revised" content="@ViewBag.Revised" />
    <meta http-equiv="Content-Language" content="da" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
    <div id="header">
        <h1>
            uncas.dk</h1>
        <ul id="menu">
            <li>@Html.ActionLink("Forside", "Index", "Home")</li>
            <li>@Html.ActionLink("Nyheder", "Index", "BlogPost")</li>
            <li>@Html.ActionLink("Ændringer", "Changes", "Home")</li>
            @if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Facts", "Index", "Fact")</li>
                <li>@Html.ActionLink("Nyheds-admin", "Admin", "BlogPost")</li>
                <li><a href="/elmah" target="_blank">Fejl</a></li>
            }
            @if (User.Identity.IsAuthenticated)
            {
                <li>@Html.ActionLink("Log '" + User.Identity.Name + "' af", "LogOff", "Authentication")</li>
            }
            else
            {            
                <li>@Html.ActionLink("Log på", "LogOn", "Authentication")</li>
            }
        </ul>
    </div>
    <div id="content">
        @RenderBody()
    </div>
    <div id="footer">
    </div>
    @MiniProfiler.RenderIncludes()
</body>
</html>

src/Uncas.NowSite.Web/Views/Shared/_MINIPROFILER UPDATED Layout.cshtml
@* Required so you have extention methods for client timings *@
@using StackExchange.Profiling;
<!DOCTYPE html>
<html>
<head>
    @* optional (enable client timing framework) *@ 
    @this.InitClientTimings()
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>

    @* optional time scripts in the header *@ 
    @this.TimeScript("Content Site.css", 
        @<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />)
    @this.TimeScript("jQuery 1.5.1", 
        @<script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>)
    @this.TimeScript("modernizr", 
        @<script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>)
    
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
    @* Make sure you've added this one line to your LAYOUT or MASTER PAGE *@
    @MiniProfiler.RenderIncludes()
</body>
</html>